version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: stressT
      POSTGRES_USER: processor
      POSTGRES_PASSWORD: key_root1234
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
